# Generated by Django 4.2.22 on 2025-06-09 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FetchLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('post', 'Post'), ('story', 'Story')], db_index=True, max_length=10)),
                ('last_checked_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='LineUser',
            fields=[
                ('uid', models.BigIntegerField(db_index=True, primary_key=True, serialize=False)),
                ('followed_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('post', 'Post'), ('story', 'Story')], db_index=True, max_length=10)),
                ('shortcode', models.CharField(blank=True, max_length=100, null=True)),
                ('media_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instagram_notifier.lineuser')),
            ],
        ),
        migrations.CreateModel(
            name='MediaDeletionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=255)),
                ('shortcode', models.CharField(max_length=64)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
