import os

TARGET_INSTAGRAM_USERNAME=os.getenv("TARGET_INSTAGRAM_USERNAME") 
MY_INSTAGRAM_USERNAME=os.getenv("MY_INSTAGRAM_USERNAME")  
LINE_NOTIFY_TOKEN=os.getenv("LINE_NOTIFY_TOKEN")
SERVICE_ACCOUNT_FILE=os.getenv("SERVICE_ACCOUNT_FILE")
STORY_DRIVE_FOLDER_ID=os.getenv("STORY_DRIVE_FOLDER_ID")
POST_DRIVE_FOLDER_ID=os.getenv("POST_DRIVE_FOLDER_ID")
SITE_URL=os.getenv("SITE_URL")
